#!/usr/bin/env python3
"""
Task 0. Writing strings to Redis
Task 1. Reading from Redis and recovering original type
"""

import redis
from uuid import uuid4
from typing import Union, Callable, Optional


class Cache:
    """
    A class to represent a cache.
    """

    def __init__(self):
        """
        Constructs all the necessary attributes for the cache object.
        """

        self._redis = redis.Redis()
        self._redis.flushdb()

    def store(self, data: Union[str, bytes, int, float]) -> str:
        """
        This function Store input data in Redis using
        a random key generated by uuid4().

        Args:
            data (str): The data to be stored in Redis.

        Returns:
            str: The random key generated by uuid4().
        """

        key = str(uuid4())
        self._redis.set(key, data)
        return key

    def get(self, key: str, fn: Optional[Callable] = None) -> Optional[str]:
        """
        Retrieve data from Redis using the specified key.

        Args:
            key (str): The key used to retrieve data from Redis.
            fn (Optional[Callable]): An optional callable used to convert
            the data back to the desired format.

        Returns:
            Optional[str]: The data retrieved from Redis as a string.
        """

        data = self._redis.get(key)
        if data is not None and fn is not None:
            return fn(data)
        return data

    def get_str(self, key: str) -> Optional[str]:
        """
        Retrieve string data from Redis using the specified key.

        Args:
            key (str): The key used to retrieve string data from Redis.

        Returns:
            Optional[str]: The string data retrieved from Redis.
        """

        return self.get(key)

    def get_int(self, key: str) -> Optional[int]:
        """
        Retrieve integer data from Redis using the specified key.

        Args:
            key (str): The key used to retrieve integer data from Redis.

        Returns:
            Optional[int]: The integer data retrieved from Redis.
        """

        return self.get(key, fn=int)
